spring:
  application:
    name: sentinelpay

  datasource:
    url: jdbc:postgresql://localhost:5432/sentinelpay_db?
    username: sentinelpay_user
    password: sentinelpay_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.sentinelpay: DEBUG
    org.hibernate.SQL: DEBUG

sentinelpay:
  security:
    jwt:
      secret: "CHANGE_THIS_TO_A_LONG_SECRET_KEY_FOR_LOCAL_DEVELOPMENT_ONLY_123456789_CHANGE_ME"
      access-token-expiration-minutes: 15
      refresh-token-expiration-days: 30
      issuer: "sentinelpay-api"