package com.sentinelpay.audit.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,

    TRANSACTION_CREATED,
    TRANSACTION_APPROVED,
    TRANSACTION_BLOCKED,
    TRANSACTION_FAILED,
    TRANSACTION_CANCELLED,

    FRAUD_CASE_CREATED,
    FRAUD_CASE_ASSIGNED,
    FRAUD_CASE_CLOSED,

    ROLE_ASSIGNED,
    ROLE_REMOVED,

    TOKEN_REFRESHED,
    TOKEN_REFRESH_FAILED,

    USER_LOGOUT,
    USER_LOGOUT_FAILED,
}